### ISSUE TITLE
Matlab Standalone Application Issue with @dynamometer

### ISSUE THREAD

**Issue by SSDad** [lionel-rigoux/vernier-toolbox#6]
Hi, Lionel,

I wrote a simple Matlab code using your Vernier-tool to read data from Vernier GoLink.  It is a very nice tool and runs well in Matlab.  However, after compiling my code to create a standalone application, the app does not read data anymore.  Any idea why?  Help will be very appreciated.  FYI, I put the @dynamometer folder and my Matlab code in same folder.

Best,

Z

**Comment by lionel-rigoux** [comment]
Hi!
Thanks for your feedback, I'm glad to see this code used!
It's hard to give you a solution without more details, but my first guess is that the problem comes from the fact the toolbox relies on mex files and those mex files rely on shared dynamic libraries (libGoIO files in @dynamometer/private, compiled from the vernier.SDK). The Matlab compiler cannot find those dependencies by default, you need to add them manually: https://de.mathworks.com/help/compiler/excel/mex-files-dlls-or-shared-libraries.html
If this does not solve you problem, could you try to print some debugging logs to narrow down the issue?

**Comment by SSDad** [comment]
Hi, Lionel,

It worked after manually adding those dependencies.  Many thanks for your help!

Z
